name: ghcr-cleanup

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old container versions
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: openbyte
          package-type: container
          min-versions-to-keep: 20
          ignore-versions: |
            ^latest$
            ^edge$
            ^\d+\.\d+\.\d+$
            ^\d+\.\d+$
            ^\d+$
